version: "3"
services:
  hangman-game-app:
    container_name: hangman-game-app
    image: hangman-game:latest
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      - MYSQL_CONTAINER=mysqldb
      - MYSQL_CONTAINER_PORT=3306
    depends_on:
      -  mysqldb
 
  mysqldb:
    image: mysql:latest
    volumes:
      - C:\MYSQL_CONTAINER_DATA:/var/lib/mysql 
    environment:
      - MYSQL_USER=ivanb
      - MYSQL_PASSWORD=ivanbproxiad
      - MYSQL_ROOT_PASSWORD=ivanbproxiad
      - MYSQL_DATABASE=hangman-game-db
    ports:
      - 3307:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ivanbproxiad --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10