---
spring:
  datasource:
    username: ivanb
    url: jdbc:mysql://host.docker.internal:3306/hangman-game-db
    password: ${hangman_db_pass}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update 
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
server:
  servlet:
    context-path: /hangman-game
cxf:
  path: /soap-services 
...