---
spring:
  datasource:
    username: ivanb
    url: jdbc:mysql://${MYSQL_CONTAINER:localhost}:${MYSQL_CONTAINER_PORT:3306}/hangman-game-db
    password: ${hangman_db_pass}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
cxf:
  path: /soap-services 
...