
package it.com.proxiad.hangmangame.logic.ranking.soapconsumer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RankingWebServiceImplService", targetNamespace = "http://ranking.logic.hangmangame.proxiad.com/", wsdlLocation = "file:/C:/JavaTraineeTasks/hangman-game/src/test/java/it/resources/HangmanGameRankingWS.wsdl")
public class RankingWebServiceImplService
    extends Service
{

    private final static URL RANKINGWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RANKINGWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RANKINGWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ranking.logic.hangmangame.proxiad.com/", "RankingWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/JavaTraineeTasks/hangman-game/src/test/java/it/resources/HangmanGameRankingWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RANKINGWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RANKINGWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RankingWebServiceImplService() {
        super(__getWsdlLocation(), RANKINGWEBSERVICEIMPLSERVICE_QNAME);
    }

    public RankingWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RANKINGWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public RankingWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RANKINGWEBSERVICEIMPLSERVICE_QNAME);
    }

    public RankingWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RANKINGWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public RankingWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RankingWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HangmanGameRankingWS
     */
    @WebEndpoint(name = "RankingWebServiceImplPort")
    public HangmanGameRankingWS getRankingWebServiceImplPort() {
        return super.getPort(new QName("http://ranking.logic.hangmangame.proxiad.com/", "RankingWebServiceImplPort"), HangmanGameRankingWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HangmanGameRankingWS
     */
    @WebEndpoint(name = "RankingWebServiceImplPort")
    public HangmanGameRankingWS getRankingWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ranking.logic.hangmangame.proxiad.com/", "RankingWebServiceImplPort"), HangmanGameRankingWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RANKINGWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RANKINGWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return RANKINGWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
