INSERT INTO game_word (content) VALUES
	('stack'),
	('class'),
	('kilobyte'),
	('syndrome'),
	('buffalo'),
	('fluffiness'),
	('awkward'),
	('beekeeper'),
	('gossip'),
	('puppy'),
	('wizard'),
	('voodoo'),
	('subway'),
	('blizzard'),
	('nightclub'),
	('zombie'),
	('whiskey');